In [20]:
import pandas as pd
import numpy as np

In [21]:
mortalidade = pd.read_csv('Mortalidade_Geral_2026.csv', sep=';',parse_dates=['DTOBITO', 'DTNASC'])

/var/folders/vx/8djkmzzj2618j015w3yn7sqm0000gn/T/ipykernel_2029/3629018022.py:1: DtypeWarning: Columns (0: CAUSAMAT) have mixed types. Specify dtype option on import or set low_memory=False.
  mortalidade = pd.read_csv('Mortalidade_Geral_2026.csv', sep=';',parse_dates=['DTOBITO', 'DTNASC'])
/var/folders/vx/8djkmzzj2618j015w3yn7sqm0000gn/T/ipykernel_2029/3629018022.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  mortalidade = pd.read_csv('Mortalidade_Geral_2026.csv', sep=';',parse_dates=['DTOBITO', 'DTNASC'])
/var/folders/vx/8djkmzzj2618j015w3yn7sqm0000gn/T/ipykernel_2029/3629018022.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  mortalidade = pd.read_csv('Mortalidade_Geral_2026.csv', sep=';',parse_dates=['DTOBITO', 'DTNASC'])

In [22]:
mortalidade.head()

,contador,ORIGEM,TIPOBITO,DTOBITO,HORAOBITO,NATURAL,CODMUNNATU,DTNASC,IDADE,SEXO,...,TPRESGINFO,TPNIVELINV,DTCADINF,MORTEPARTO,DTCONCASO,ALTCAUSA,CAUSABAS_O,TPPOS,TP_ALTERA,CB_ALT
0,1,1,2,03042026,2315.0,NaN,NaN,06021928,498,2,...,NaN,NaN,NaN,NaN,NaN,NaN,I499,N,NaN,NaN
1,2,1,2,11032026,845.0,843.0,431690.0,02081935,490,1,...,NaN,NaN,NaN,NaN,NaN,NaN,C857,N,NaN,NaN
2,3,1,2,28012026,1340.0,823.0,230530.0,24051974,451,1,...,NaN,NaN,NaN,NaN,NaN,NaN,I210,N,NaN,NaN
3,4,1,2,07022026,NaN,823.0,230530.0,08021929,496,2,...,NaN,NaN,NaN,NaN,NaN,NaN,R961,N,NaN,NaN
4,5,1,2,19022026,1620.0,823.0,230530.0,17081930,495,2,...,NaN,NaN,NaN,NaN,NaN,NaN,R961,N,NaN,NaN

In [23]:
mortalidade.info()

<class 'pandas.DataFrame'>
RangeIndex: 506531 entries, 0 to 506530
Data columns (total 86 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   contador    506531 non-null  int64
 1   ORIGEM      506531 non-null  int64
 2   TIPOBITO    506531 non-null  int64
 3   DTOBITO     506531 non-null  str
 4   HORAOBITO   491792 non-null  float64
 5   NATURAL     491086 non-null  float64
 6   CODMUNNATU  485169 non-null  float64
 7   DTNASC      505904 non-null  str
 8   IDADE       506531 non-null  int64
 9   SEXO        506531 non-null  int64
 10  RACACOR     500286 non-null  float64
 11  ESTCIV      486504 non-null  float64
 12  ESC         481760 non-null  float64
 13  ESC2010     477991 non-null  float64
 14  SERIESCFAL  154717 non-null  float64
 15  OCUP        446342 non-null  float64
 16  CODMUNRES   506531 non-null  int64
 17  LOCOCOR     506531 non-null  int64
 18  CODESTAB    376272 non-null  float64
 19  CODMUNOCOR  506531 non-null  int64
 20  IDADEMAE    9656 non-null    float64
 21  ESCMAE      9538 non-null    float64
 22  ESCMAE2010  9430 non-null    float64
 23  SERIESCMAE  4164 non-null    float64
 24  OCUPMAE     8729 non-null    float64
 25  QTDFILVIVO  9633 non-null    float64
 26  QTDFILMORT  9361 non-null    float64
 27  GRAVIDEZ    9862 non-null    float64
 28  SEMAGESTAC  9416 non-null    float64
 29  GESTACAO    9416 non-null    float64
 30  PARTO       9832 non-null    float64
 31  OBITOPARTO  9756 non-null    float64
 32  PESO        9554 non-null    float64
 33  TPMORTEOCO  26936 non-null   float64
 34  OBITOGRAV   27217 non-null   float64
 35  OBITOPUERP  27211 non-null   float64
 36  ASSISTMED   350614 non-null  float64
 37  EXAME       2412 non-null    float64
 38  CIRURGIA    2363 non-null    float64
 39  NECROPSIA   361880 non-null  float64
 40  LINHAA      495935 non-null  str
 41  LINHAB      395245 non-null  str
 42  LINHAC      252323 non-null  str
 43  LINHAD      106509 non-null  str
 44  LINHAII     216762 non-null  str
 45  CAUSABAS    506531 non-null  str
 46  CB_PRE      0 non-null       float64
 47  COMUNSVOIM  90635 non-null   float64
 48  DTATESTADO  505032 non-null  float64
 49  CIRCOBITO   50335 non-null   float64
 50  ACIDTRAB    17986 non-null   float64
 51  FONTE       40742 non-null   float64
 52  NUMEROLOTE  506499 non-null  float64
 53  DTINVESTIG  49998 non-null   float64
 54  DTCADASTRO  506443 non-null  float64
 55  ATESTANTE   475514 non-null  float64
 56  STCODIFICA  506025 non-null  str
 57  CODIFICADO  506499 non-null  str
 58  VERSAOSIST  506499 non-null  str
 59  VERSAOSCB   501833 non-null  float64
 60  FONTEINV    50907 non-null   float64
 61  DTRECEBIM   506500 non-null  float64
 62  ATESTADO    506531 non-null  str
 63  DTRECORIGA  506531 non-null  int64
 64  OPOR_DO     506531 non-null  int64
 65  CAUSAMAT    9 non-null       str
 66  ESCMAEAGR1  9430 non-null    float64
 67  ESCFALAGR1  477991 non-null  float64
 68  STDOEPIDEM  506499 non-null  float64
 69  STDONOVA    506531 non-null  int64
 70  DIFDATA     506531 non-null  int64
 71  NUDIASOBCO  12631 non-null   float64
 72  DTCADINV    12730 non-null   float64
 73  TPOBITOCOR  12730 non-null   float64
 74  DTCONINV    12625 non-null   float64
 75  FONTES      4562 non-null    str
 76  TPRESGINFO  478 non-null     float64
 77  TPNIVELINV  12736 non-null   str
 78  DTCADINF    4565 non-null    float64
 79  MORTEPARTO  4565 non-null    float64
 80  DTCONCASO   4087 non-null    float64
 81  ALTCAUSA    4343 non-null    float64
 82  CAUSABAS_O  505541 non-null  str
 83  TPPOS       332683 non-null  str
 84  TP_ALTERA   10323 non-null   float64
 85  CB_ALT      2427 non-null    str
dtypes: float64(56), int64(12), str(18)
memory usage: 332.3 MB

In [59]:
municipios = pd.read_excel('MUNICIPIOS.xlsx')

In [25]:
municipios.head()

   CODMUNRES                MUNICIPIO  UF
0     355030                SÃO PAULO  SP
1     120030                    FEIJÓ  AC
2     251600                  SOLÂNEA  PB
3     260290  CABO DE SANTO AGOSTINHO  PE
4     230210                 BATURITÉ  CE

In [57]:
mortalidade = mortalidade.merge(municipios, how='left', left_on='CODMUNNATU', right_on='CODMUNRES')

In [29]:
mortalidade.head()

,contador,ORIGEM,TIPOBITO,DTOBITO,HORAOBITO,NATURAL,CODMUNNATU,DTNASC,IDADE,SEXO,...,MORTEPARTO,DTCONCASO,ALTCAUSA,CAUSABAS_O,TPPOS,TP_ALTERA,CB_ALT,CODMUNRES_y,MUNICIPIO,UF
0,1,1,2,03042026,2315.0,NaN,NaN,06021928,498,2,...,NaN,NaN,NaN,I499,N,NaN,NaN,NaN,NaN,NaN
1,2,1,2,11032026,845.0,843.0,431690.0,02081935,490,1,...,NaN,NaN,NaN,C857,N,NaN,NaN,431690.0,SANTA MARIA,RS
2,3,1,2,28012026,1340.0,823.0,230530.0,24051974,451,1,...,NaN,NaN,NaN,I210,N,NaN,NaN,230530.0,IBIAPINA,CE
3,4,1,2,07022026,NaN,823.0,230530.0,08021929,496,2,...,NaN,NaN,NaN,R961,N,NaN,NaN,230530.0,IBIAPINA,CE
4,5,1,2,19022026,1620.0,823.0,230530.0,17081930,495,2,...,NaN,NaN,NaN,R961,N,NaN,NaN,230530.0,IBIAPINA,CE

In [51]:
mortalidade.info()

<class 'pandas.DataFrame'>
RangeIndex: 506531 entries, 0 to 506530
Data columns (total 89 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   contador     506531 non-null  int64
 1   ORIGEM       506531 non-null  int64
 2   TIPOBITO     506531 non-null  int64
 3   DTOBITO      506531 non-null  str
 4   HORAOBITO    491792 non-null  float64
 5   NATURAL      491086 non-null  float64
 6   CODMUNNATU   485169 non-null  float64
 7   DTNASC       505904 non-null  str
 8   IDADE        506531 non-null  int64
 9   SEXO         506531 non-null  int64
 10  RACACOR      500286 non-null  float64
 11  ESTCIV       486504 non-null  float64
 12  ESC          481760 non-null  float64
 13  ESC2010      477991 non-null  float64
 14  SERIESCFAL   154717 non-null  float64
 15  OCUP         446342 non-null  float64
 16  CODMUNRES_x  506531 non-null  int64
 17  LOCOCOR      506531 non-null  int64
 18  CODESTAB     376272 non-null  float64
 19  CODMUNOCOR   506531 non-null  int64
 20  IDADEMAE     9656 non-null    float64
 21  ESCMAE       9538 non-null    float64
 22  ESCMAE2010   9430 non-null    float64
 23  SERIESCMAE   4164 non-null    float64
 24  OCUPMAE      8729 non-null    float64
 25  QTDFILVIVO   9633 non-null    float64
 26  QTDFILMORT   9361 non-null    float64
 27  GRAVIDEZ     9862 non-null    float64
 28  SEMAGESTAC   9416 non-null    float64
 29  GESTACAO     9416 non-null    float64
 30  PARTO        9832 non-null    float64
 31  OBITOPARTO   9756 non-null    float64
 32  PESO         9554 non-null    float64
 33  TPMORTEOCO   26936 non-null   float64
 34  OBITOGRAV    27217 non-null   float64
 35  OBITOPUERP   27211 non-null   float64
 36  ASSISTMED    350614 non-null  float64
 37  EXAME        2412 non-null    float64
 38  CIRURGIA     2363 non-null    float64
 39  NECROPSIA    361880 non-null  float64
 40  LINHAA       495935 non-null  str
 41  LINHAB       395245 non-null  str
 42  LINHAC       252323 non-null  str
 43  LINHAD       106509 non-null  str
 44  LINHAII      216762 non-null  str
 45  CAUSABAS     506531 non-null  str
 46  CB_PRE       0 non-null       float64
 47  COMUNSVOIM   90635 non-null   float64
 48  DTATESTADO   505032 non-null  float64
 49  CIRCOBITO    50335 non-null   float64
 50  ACIDTRAB     17986 non-null   float64
 51  FONTE        40742 non-null   float64
 52  NUMEROLOTE   506499 non-null  float64
 53  DTINVESTIG   49998 non-null   float64
 54  DTCADASTRO   506443 non-null  float64
 55  ATESTANTE    475514 non-null  float64
 56  STCODIFICA   506025 non-null  str
 57  CODIFICADO   506499 non-null  str
 58  VERSAOSIST   506499 non-null  str
 59  VERSAOSCB    501833 non-null  float64
 60  FONTEINV     50907 non-null   float64
 61  DTRECEBIM    506500 non-null  float64
 62  ATESTADO     506531 non-null  str
 63  DTRECORIGA   506531 non-null  int64
 64  OPOR_DO      506531 non-null  int64
 65  CAUSAMAT     9 non-null       str
 66  ESCMAEAGR1   9430 non-null    float64
 67  ESCFALAGR1   477991 non-null  float64
 68  STDOEPIDEM   506499 non-null  float64
 69  STDONOVA     506531 non-null  int64
 70  DIFDATA      506531 non-null  int64
 71  NUDIASOBCO   12631 non-null   float64
 72  DTCADINV     12730 non-null   float64
 73  TPOBITOCOR   12730 non-null   float64
 74  DTCONINV     12625 non-null   float64
 75  FONTES       4562 non-null    str
 76  TPRESGINFO   478 non-null     float64
 77  TPNIVELINV   12736 non-null   str
 78  DTCADINF     4565 non-null    float64
 79  MORTEPARTO   4565 non-null    float64
 80  DTCONCASO    4087 non-null    float64
 81  ALTCAUSA     4343 non-null    float64
 82  CAUSABAS_O   505541 non-null  str
 83  TPPOS        332683 non-null  str
 84  TP_ALTERA    10323 non-null   float64
 85  CB_ALT       2427 non-null    str
 86  CODMUNRES_y  484794 non-null  float64
 87  MUNICIPIO    484794 non-null  str
 88  UF           484794 non-null  str
dtypes: float64(57), int64(12), str(20)
memory usage: 343.9 MB

In [48]:
mortalidade['CODMUNNATU'].isnull().sum()

np.int64(21362)

In [49]:
mortalidade['MUNICIPIO'].isnull().sum()

np.int64(21737)

In [54]:
municipios_nao_encontrados = mortalidade[mortalidade['CODMUNNATU'].notna() & mortalidade['MUNICIPIO'].isna()]

In [55]:
municipios_nao_encontrados.head()

,contador,ORIGEM,TIPOBITO,DTOBITO,HORAOBITO,NATURAL,CODMUNNATU,DTNASC,IDADE,SEXO,...,MORTEPARTO,DTCONCASO,ALTCAUSA,CAUSABAS_O,TPPOS,TP_ALTERA,CB_ALT,CODMUNRES_y,MUNICIPIO,UF
475,476,1,2,26022026,2338.0,843.0,430000.0,13011947,479,2,...,NaN,NaN,NaN,C19,NaN,NaN,NaN,NaN,NaN,NaN
1575,1576,1,2,06012026,900.0,843.0,430000.0,25051947,478,2,...,NaN,NaN,NaN,E118,NaN,NaN,NaN,NaN,NaN,NaN
1677,1678,1,2,21022026,41.0,812.0,120000.0,03031948,477,1,...,NaN,NaN,NaN,I219,N,NaN,NaN,NaN,NaN,NaN
8611,8612,1,2,19032026,335.0,843.0,430000.0,17091945,480,1,...,NaN,NaN,NaN,J439,NaN,NaN,NaN,NaN,NaN,NaN
23773,23774,1,2,21012026,1000.0,827.0,270000.0,17081948,477,1,...,NaN,NaN,NaN,R99,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# fiz o merge somente com o codigo do municipio de nascimento, mas apareceram algum valores que nao possuem correspondencia na tabela de municipios, pelo que analisei, 
# sao codigos genericos que só tem os primeiros digitos (que corresponde a UF)
# dependendo da analise que iremos fazer, talvez faça sentido fazer o merge com o codigo do municipio da morte, mas estava fazendo pra treinar também

In [60]:
cid = pd.read_excel('CIDs_com_descricao.xlsx')

In [61]:
cid.head()

  CAUSABAS                                      DESCRICAO_CID
0     J449  Doença pulmonar obstrutiva crônica não especif...
1     W749  Afogamento e submersão não especificados - loc...
2     E149  Diabetes mellitus não especificado - sem compl...
3      C61                      Neoplasia maligna da próstata
4     G309               Doença de Alzheimer não especificada

In [83]:
mortalidade[['CAUSABAS_O','LINHAA']]

       CAUSABAS_O LINHAA
0            I499  *J960
1            C857  *E440
2            I210  *I469
3            R961  *R961
4            R961  *J960
...           ...    ...
506526       C945  *R571
506527        D68  *I212
506528        I10  *I219
506529       I219  *R570
506530       I219  *R570

[506531 rows x 2 columns]

In [ ]:
# em relacao ao cid, tem mais de um campo com essa informacao, mas nao sei o que é melhor para considerarmos. se é o causabas_o ou o linhaa. 
# pelo que entendi um deles é o do atestado de obito, mas como dá pra ver no codigo acima, as informacoes nao batem.