In [2]:
import pandas as pd
import numpy as np

In [3]:
# 1. Define a lista de colunas que serão importadas
colunas_desejadas = [
    'TIPOBITO',
    'DTOBITO',
    'DTNASC',
    'IDADE',
    'SEXO',
    'RACACOR',
    'ESTCIV',
    'ESC2010',
    'OCUP',
    'CODMUNRES',
    'CODMUNOCOR',
    'CAUSABAS'
]

# 2. Defina os tipos de dados das colunas
tipos_dados = {
    'TIPOBITO': str,
    'IDADE': str,       # Mantém como texto para não perder os zeros à esquerda da codificação do DATASUS
    'SEXO': str,
    'RACACOR': str,
    'ESTCIV': str,
    'ESC2010': str,
    'OCUP': str,
    'CODMUNRES': int,
    'CODMUNOCOR': str,
    'CAUSABAS': str     # Garante que códigos CID mistos não gerem alertas
}

# 3. Importa o arquivo CSV de forma otimizada
mortalidade = pd.read_csv(
    'Mortalidade_Geral_2026.csv',
    sep=';',
    usecols=colunas_desejadas,
    dtype=tipos_dados,
    parse_dates=['DTOBITO', 'DTNASC'],
    date_format='%d/%m/%Y'
)

# 4. Converte DTOBITO e DTNASC (formato: ddmmYYYY) para uma data real do Pandas (formato: YYYY-mm-dd)
mortalidade['DTOBITO'] = pd.to_datetime(mortalidade['DTOBITO'], format='%d%m%Y', errors='coerce')
mortalidade['DTNASC'] = pd.to_datetime(mortalidade['DTNASC'], format='%d%m%Y', errors='coerce')

In [4]:
mortalidade.head()

,TIPOBITO,DTOBITO,DTNASC,IDADE,SEXO,RACACOR,ESTCIV,ESC2010,OCUP,CODMUNRES,CODMUNOCOR,CAUSABAS
0,2,2026-04-03,1928-02-06,498,2,1,3,NaN,999992,310620,310620,I499
1,2,2026-03-11,1935-08-02,490,1,1,2,1,999993,430258,430258,C857
2,2,2026-01-28,1974-05-24,451,1,4,9,2,622020,230530,230530,I210
3,2,2026-02-07,1929-02-08,496,2,1,3,1,622020,230530,230530,R961
4,2,2026-02-19,1930-08-17,495,2,1,1,0,622020,230530,230530,R961

In [5]:
mortalidade.info()

<class 'pandas.DataFrame'>
RangeIndex: 506531 entries, 0 to 506530
Data columns (total 12 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   TIPOBITO    506531 non-null  str
 1   DTOBITO     506531 non-null  datetime64[us]
 2   DTNASC      505904 non-null  datetime64[us]
 3   IDADE       506531 non-null  str
 4   SEXO        506531 non-null  str
 5   RACACOR     500286 non-null  str
 6   ESTCIV      486504 non-null  str
 7   ESC2010     477991 non-null  str
 8   OCUP        446342 non-null  str
 9   CODMUNRES   506531 non-null  int64
 10  CODMUNOCOR  506531 non-null  str
 11  CAUSABAS    506531 non-null  str
dtypes: datetime64[us](2), int64(1), str(9)
memory usage: 46.4 MB

In [6]:
municipios = pd.read_excel('MUNICIPIOS.xlsx')

In [7]:
municipios.head()

   CODMUNRES                MUNICIPIO  UF   POPULAÇÃO
0     355030                SÃO PAULO  SP  12200180.0
1     120030                    FEIJÓ  AC     35035.0
2     251600                  SOLÂNEA  PB     26777.0
3     260290  CABO DE SANTO AGOSTINHO  PE    203084.0
4     230210                 BATURITÉ  CE     33335.0

In [8]:
municipios.info()

<class 'pandas.DataFrame'>
RangeIndex: 5580 entries, 0 to 5579
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   CODMUNRES  5580 non-null   int64
 1   MUNICIPIO  5580 non-null   str
 2   UF         5580 non-null   str
 3   POPULAÇÃO  5559 non-null   float64
dtypes: float64(1), int64(1), str(2)
memory usage: 174.5 KB

In [9]:
mortalidade = mortalidade.merge(municipios, how='left')

In [10]:
mortalidade.head()

,TIPOBITO,DTOBITO,DTNASC,IDADE,SEXO,RACACOR,ESTCIV,ESC2010,OCUP,CODMUNRES,CODMUNOCOR,CAUSABAS,MUNICIPIO,UF,POPULAÇÃO
0,2,2026-04-03,1928-02-06,498,2,1,3,NaN,999992,310620,310620,I499,BELO HORIZONTE,MG,2392678.0
1,2,2026-03-11,1935-08-02,490,1,1,2,1,999993,430258,430258,C857,BOZANO,RS,2135.0
2,2,2026-01-28,1974-05-24,451,1,4,9,2,622020,230530,230530,I210,IBIAPINA,CE,23966.0
3,2,2026-02-07,1929-02-08,496,2,1,3,1,622020,230530,230530,R961,IBIAPINA,CE,23966.0
4,2,2026-02-19,1930-08-17,495,2,1,1,0,622020,230530,230530,R961,IBIAPINA,CE,23966.0

In [11]:
mortalidade.info()

<class 'pandas.DataFrame'>
RangeIndex: 506531 entries, 0 to 506530
Data columns (total 15 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   TIPOBITO    506531 non-null  str
 1   DTOBITO     506531 non-null  datetime64[us]
 2   DTNASC      505904 non-null  datetime64[us]
 3   IDADE       506531 non-null  str
 4   SEXO        506531 non-null  str
 5   RACACOR     500286 non-null  str
 6   ESTCIV      486504 non-null  str
 7   ESC2010     477991 non-null  str
 8   OCUP        446342 non-null  str
 9   CODMUNRES   506531 non-null  int64
 10  CODMUNOCOR  506531 non-null  str
 11  CAUSABAS    506531 non-null  str
 12  MUNICIPIO   506531 non-null  str
 13  UF          506531 non-null  str
 14  POPULAÇÃO   506001 non-null  float64
dtypes: datetime64[us](2), float64(1), int64(1), str(11)
memory usage: 58.0 MB

In [12]:
cid = pd.read_excel('CIDs_com_descricao.xlsx')

In [13]:
cid.head()

  CAUSABAS                                      DESCRICAO_CID
0     J449  Doença pulmonar obstrutiva crônica não especif...
1     W749  Afogamento e submersão não especificados - loc...
2     E149  Diabetes mellitus não especificado - sem compl...
3      C61                      Neoplasia maligna da próstata
4     G309               Doença de Alzheimer não especificada

In [14]:
mortalidade = mortalidade.merge(cid, how='left', left_on='CAUSABAS', right_on='CAUSABAS')

In [15]:
mortalidade.head()

,TIPOBITO,DTOBITO,DTNASC,IDADE,SEXO,RACACOR,ESTCIV,ESC2010,OCUP,CODMUNRES,CODMUNOCOR,CAUSABAS,MUNICIPIO,UF,POPULAÇÃO,DESCRICAO_CID
0,2,2026-04-03,1928-02-06,498,2,1,3,NaN,999992,310620,310620,I499,BELO HORIZONTE,MG,2392678.0,Arritmia cardíaca não especificada
1,2,2026-03-11,1935-08-02,490,1,1,2,1,999993,430258,430258,C857,BOZANO,RS,2135.0,Outros tipos especificados de linfoma não-Hodgkin
2,2,2026-01-28,1974-05-24,451,1,4,9,2,622020,230530,230530,I210,IBIAPINA,CE,23966.0,Infarto agudo transmural da parede anterior do...
3,2,2026-02-07,1929-02-08,496,2,1,3,1,622020,230530,230530,R961,IBIAPINA,CE,23966.0,Morte que ocorre em menos de 24 horas após o i...
4,2,2026-02-19,1930-08-17,495,2,1,1,0,622020,230530,230530,R961,IBIAPINA,CE,23966.0,Morte que ocorre em menos de 24 horas após o i...

In [16]:
mortalidade.info()

<class 'pandas.DataFrame'>
RangeIndex: 506531 entries, 0 to 506530
Data columns (total 16 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   TIPOBITO       506531 non-null  str
 1   DTOBITO        506531 non-null  datetime64[us]
 2   DTNASC         505904 non-null  datetime64[us]
 3   IDADE          506531 non-null  str
 4   SEXO           506531 non-null  str
 5   RACACOR        500286 non-null  str
 6   ESTCIV         486504 non-null  str
 7   ESC2010        477991 non-null  str
 8   OCUP           446342 non-null  str
 9   CODMUNRES      506531 non-null  int64
 10  CODMUNOCOR     506531 non-null  str
 11  CAUSABAS       506531 non-null  str
 12  MUNICIPIO      506531 non-null  str
 13  UF             506531 non-null  str
 14  POPULAÇÃO      506001 non-null  float64
 15  DESCRICAO_CID  497487 non-null  str
dtypes: datetime64[us](2), float64(1), int64(1), str(12)
memory usage: 61.8 MB

In [17]:
mortalidade['CAUSABAS'].isna().sum()

np.int64(0)

In [18]:
mortalidade['DESCRICAO_CID'].isna().sum()

np.int64(9044)

In [19]:
mortalidade.loc[mortalidade['DESCRICAO_CID'].isna(), ['CAUSABAS', 'DESCRICAO_CID']].head(10)

    CAUSABAS DESCRICAO_CID
107     L899           NaN
159     A090           NaN
200     C809           NaN
243     A090           NaN
301     J987           NaN
346     C809           NaN
370     C809           NaN
441     C800           NaN
447     N185           NaN
489     A090           NaN

In [20]:
cid.loc[cid['DESCRICAO_CID'].isna(), ['CAUSABAS', 'DESCRICAO_CID']]

     CAUSABAS DESCRICAO_CID
110      A099           NaN
114      C809           NaN
197      L899           NaN
199      N185           NaN
201      R572           NaN
...       ...           ...
4096     O979           NaN
4366     C965           NaN
4397      G40           NaN
4404     D474           NaN
4420     I725           NaN

[89 rows x 2 columns]

In [21]:
# tem 89 CIDs que estao na planilha de CIDs, mas nao tem descricao.

In [22]:
cid.loc[cid['CAUSABAS']=='A090', ['CAUSABAS', 'DESCRICAO_CID']]

    CAUSABAS DESCRICAO_CID
381     A090           NaN

In [24]:
mortalidade['DESCRICAO_CID'].value_counts().head(10)

DESCRICAO_CID
Infarto agudo do miocárdio não especificado                                   27211
Pneumonia não especificada                                                    20220
Outras causas mal definidas e as não especificadas de mortalidade             17991
Infecção do trato urinário de localização não especificada                    11127
Hipertensão essencial (primária)                                              10751
Neoplasia maligna dos brônquios ou pulmões, não especificado                  10447
Acidente vascular cerebral, não especificado como hemorrágico ou isquêmico     9822
Doença de Alzheimer não especificada                                           9636
Septicemia não especificada                                                    7915
Neoplasia maligna da mama, não especificada                                    7155
Name: count, dtype: int64

In [25]:
mortalidade['MUNICIPIO'].value_counts().head(10)

MUNICIPIO
SÃO PAULO         25266
RIO DE JANEIRO    19883
FORTALEZA          6520
SALVADOR           5714
BELO HORIZONTE     5630
BRASILIA           5168
CURITIBA           4709
RECIFE             4427
PORTO ALEGRE       4308
MANAUS             4167
Name: count, dtype: int64